create table sys_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null,
    email varchar(128) not null,
    password_hash varchar(255) not null,
    nickname varchar(64) not null,
    user_status varchar(32) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by bigint,
    updated_by bigint,
    password_updated_at timestamp with time zone not null default current_timestamp,
    last_login_at timestamp with time zone,
    last_login_ip varchar(64),
    account_locked_at timestamp with time zone,
    disabled_reason varchar(255),
    constraint uk_sys_user_username unique (username),
    constraint uk_sys_user_email unique (email),
    constraint ck_sys_user_status check (user_status in ('ACTIVE', 'DISABLED', 'LOCKED', 'DELETED'))
);

create table sys_role (
    id bigint generated by default as identity primary key,
    role_code varchar(64) not null,
    role_name varchar(64) not null,
    role_status varchar(32) not null default 'ACTIVE',
    remark varchar(255),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by bigint,
    updated_by bigint,
    role_type varchar(32) not null default 'SYSTEM',
    is_builtin boolean not null default false,
    sort_order integer not null default 100,
    disabled_reason varchar(255),
    constraint uk_sys_role_role_code unique (role_code),
    constraint ck_sys_role_status check (role_status in ('ACTIVE', 'DISABLED')),
    constraint ck_sys_role_type check (role_type in ('SYSTEM', 'EXTENSION', 'RESERVED'))
);

create table sys_user_role (
    user_id bigint not null,
    role_id bigint not null,
    created_at timestamp with time zone not null default current_timestamp,
    created_by bigint,
    assignment_status varchar(32) not null default 'ACTIVE',
    expires_at timestamp with time zone,
    updated_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    remark varchar(255),
    primary key (user_id, role_id),
    constraint fk_sys_user_role_user foreign key (user_id) references sys_user (id),
    constraint fk_sys_user_role_role foreign key (role_id) references sys_role (id),
    constraint ck_sys_user_role_status check (assignment_status in ('ACTIVE', 'REVOKED', 'EXPIRED'))
);
